// Generated by gencpp from file virtual_dc_motor/getMotorJointsLengthsResponse.msg
// DO NOT EDIT!


#ifndef VIRTUAL_DC_MOTOR_MESSAGE_GETMOTORJOINTSLENGTHSRESPONSE_H
#define VIRTUAL_DC_MOTOR_MESSAGE_GETMOTORJOINTSLENGTHSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace virtual_dc_motor
{
template <class ContainerAllocator>
struct getMotorJointsLengthsResponse_
{
  typedef getMotorJointsLengthsResponse_<ContainerAllocator> Type;

  getMotorJointsLengthsResponse_()
    : data()  {
    }
  getMotorJointsLengthsResponse_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getMotorJointsLengthsResponse_

typedef ::virtual_dc_motor::getMotorJointsLengthsResponse_<std::allocator<void> > getMotorJointsLengthsResponse;

typedef boost::shared_ptr< ::virtual_dc_motor::getMotorJointsLengthsResponse > getMotorJointsLengthsResponsePtr;
typedef boost::shared_ptr< ::virtual_dc_motor::getMotorJointsLengthsResponse const> getMotorJointsLengthsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator1> & lhs, const ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator1> & lhs, const ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace virtual_dc_motor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e066daa5966378a57445687eb65bfa3b";
  }

  static const char* value(const ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe066daa5966378a5ULL;
  static const uint64_t static_value2 = 0x7445687eb65bfa3bULL;
};

template<class ContainerAllocator>
struct DataType< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "virtual_dc_motor/getMotorJointsLengthsResponse";
  }

  static const char* value(const ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] data\n"
"\n"
;
  }

  static const char* value(const ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getMotorJointsLengthsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::virtual_dc_motor::getMotorJointsLengthsResponse_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIRTUAL_DC_MOTOR_MESSAGE_GETMOTORJOINTSLENGTHSRESPONSE_H
