// Generated by gencpp from file virtual_dc_motor/getMotorJointsLengthsRequest.msg
// DO NOT EDIT!


#ifndef VIRTUAL_DC_MOTOR_MESSAGE_GETMOTORJOINTSLENGTHSREQUEST_H
#define VIRTUAL_DC_MOTOR_MESSAGE_GETMOTORJOINTSLENGTHSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace virtual_dc_motor
{
template <class ContainerAllocator>
struct getMotorJointsLengthsRequest_
{
  typedef getMotorJointsLengthsRequest_<ContainerAllocator> Type;

  getMotorJointsLengthsRequest_()
    {
    }
  getMotorJointsLengthsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct getMotorJointsLengthsRequest_

typedef ::virtual_dc_motor::getMotorJointsLengthsRequest_<std::allocator<void> > getMotorJointsLengthsRequest;

typedef boost::shared_ptr< ::virtual_dc_motor::getMotorJointsLengthsRequest > getMotorJointsLengthsRequestPtr;
typedef boost::shared_ptr< ::virtual_dc_motor::getMotorJointsLengthsRequest const> getMotorJointsLengthsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace virtual_dc_motor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "virtual_dc_motor/getMotorJointsLengthsRequest";
  }

  static const char* value(const ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getMotorJointsLengthsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::virtual_dc_motor::getMotorJointsLengthsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // VIRTUAL_DC_MOTOR_MESSAGE_GETMOTORJOINTSLENGTHSREQUEST_H
