// Generated by gencpp from file virtual_dc_motor/getMotorJointsLengths.msg
// DO NOT EDIT!


#ifndef VIRTUAL_DC_MOTOR_MESSAGE_GETMOTORJOINTSLENGTHS_H
#define VIRTUAL_DC_MOTOR_MESSAGE_GETMOTORJOINTSLENGTHS_H

#include <ros/service_traits.h>


#include <virtual_dc_motor/getMotorJointsLengthsRequest.h>
#include <virtual_dc_motor/getMotorJointsLengthsResponse.h>


namespace virtual_dc_motor
{

struct getMotorJointsLengths
{

typedef getMotorJointsLengthsRequest Request;
typedef getMotorJointsLengthsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getMotorJointsLengths
} // namespace virtual_dc_motor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::virtual_dc_motor::getMotorJointsLengths > {
  static const char* value()
  {
    return "e066daa5966378a57445687eb65bfa3b";
  }

  static const char* value(const ::virtual_dc_motor::getMotorJointsLengths&) { return value(); }
};

template<>
struct DataType< ::virtual_dc_motor::getMotorJointsLengths > {
  static const char* value()
  {
    return "virtual_dc_motor/getMotorJointsLengths";
  }

  static const char* value(const ::virtual_dc_motor::getMotorJointsLengths&) { return value(); }
};


// service_traits::MD5Sum< ::virtual_dc_motor::getMotorJointsLengthsRequest> should match
// service_traits::MD5Sum< ::virtual_dc_motor::getMotorJointsLengths >
template<>
struct MD5Sum< ::virtual_dc_motor::getMotorJointsLengthsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::virtual_dc_motor::getMotorJointsLengths >::value();
  }
  static const char* value(const ::virtual_dc_motor::getMotorJointsLengthsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::virtual_dc_motor::getMotorJointsLengthsRequest> should match
// service_traits::DataType< ::virtual_dc_motor::getMotorJointsLengths >
template<>
struct DataType< ::virtual_dc_motor::getMotorJointsLengthsRequest>
{
  static const char* value()
  {
    return DataType< ::virtual_dc_motor::getMotorJointsLengths >::value();
  }
  static const char* value(const ::virtual_dc_motor::getMotorJointsLengthsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::virtual_dc_motor::getMotorJointsLengthsResponse> should match
// service_traits::MD5Sum< ::virtual_dc_motor::getMotorJointsLengths >
template<>
struct MD5Sum< ::virtual_dc_motor::getMotorJointsLengthsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::virtual_dc_motor::getMotorJointsLengths >::value();
  }
  static const char* value(const ::virtual_dc_motor::getMotorJointsLengthsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::virtual_dc_motor::getMotorJointsLengthsResponse> should match
// service_traits::DataType< ::virtual_dc_motor::getMotorJointsLengths >
template<>
struct DataType< ::virtual_dc_motor::getMotorJointsLengthsResponse>
{
  static const char* value()
  {
    return DataType< ::virtual_dc_motor::getMotorJointsLengths >::value();
  }
  static const char* value(const ::virtual_dc_motor::getMotorJointsLengthsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VIRTUAL_DC_MOTOR_MESSAGE_GETMOTORJOINTSLENGTHS_H
