(cl:defpackage virtual_dc_motor-srv
  (:use )
  (:export
   "GETMOTORJOINTSLENGTHS"
   "<GETMOTORJOINTSLENGTHS-REQUEST>"
   "GETMOTORJOINTSLENGTHS-REQUEST"
   "<GETMOTORJOINTSLENGTHS-RESPONSE>"
   "GETMOTORJOINTSLENGTHS-RESPONSE"
  ))

